//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator_Salariu.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametrii
    {
        public int Id { get; set; }
        public double CAS { get; set; }
        public double CASS { get; set; }
        public double Impozit { get; set; }
        public string Parola { get; set; }
    }
}
