//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator_Salariu.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salariat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salariat()
        {
            this.ProcentSpor = 0;
            this.PremiiBrute = 0;
            this.Retineri = 0;
        }
    
        public int Nr_crt { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Functie { get; set; }
        public int SalariuBaza { get; set; }
        public int ProcentSpor { get; set; }
        public int PremiiBrute { get; set; }
        public Nullable<int> TotalBrut { get; set; }
        public Nullable<int> BrutImpozabil { get; set; }
        public Nullable<int> Impozit { get; set; }
        public Nullable<int> CAS { get; set; }
        public Nullable<int> CASS { get; set; }
        public int Retineri { get; set; }
        public Nullable<int> ViratCard { get; set; }
    }
}
